runtime: php72

env_variables:
  ## Put production environment variables here.
  APP_KEY: YOUR_APP_KEY
  APP_STORAGE: /tmp
  VIEW_COMPILED_PATH: /tmp
  CACHE_DRIVER: database
  SESSION_DRIVER: database
  ## Set these environment variables according to your CloudSQL configuration.
  DB_DATABASE: cccidb
  DB_USERNAME: ifechi
  DB_PASSWORD: "@ifechi"
  DB_SOCKET: "/cloudsql/cccidb:europe-west1:ccci-db"